language: python

python:
  - 3.6

services:
  - postgresql

env:
  global:
    - DATABASE_URL = postgres://postgres@localhost/test_db
    - DJANGO_SECRET_KEY = 'TravisDjangoNotSoSecretKey'

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database test_db;' -U postgres

script:
  - coverage run --source=eqar_backend manage.py test

after_success:
  - coveralls
