language: python

python:
  - 3.8

services:
  - postgresql
  - redis-server

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database test_db;' -U postgres

script:
  - coverage run --source='.' manage.py test

after_success:
  - coveralls

addons:
  postgresql: "9.4"