# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('countries', '0001_initial'),
        ('lists', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_primary', models.CharField(blank=True, max_length=100)),
                ('nqf_level', models.CharField(blank=True, max_length=10)),
                ('countries', models.ManyToManyField(to='countries.Country')),
                ('qf_ehea_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.QFEHEALevel')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report')),
            ],
            options={
                'db_table': 'deqar_programmes',
            },
        ),
        migrations.CreateModel(
            name='ProgrammeIdentifier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=50)),
                ('resource', models.CharField(blank=True, max_length=30)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.Programme')),
            ],
            options={
                'db_table': 'deqar_programme_identifiers',
            },
        ),
        migrations.CreateModel(
            name='ProgrammeName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('name_is_primary', models.BooleanField(default=False)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.Programme')),
            ],
            options={
                'db_table': 'deqar_programme_names',
                'ordering': ('name_is_primary', 'name'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='programmename',
            unique_together=set([('programme', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='programmeidentifier',
            unique_together=set([('programme', 'agency', 'resource', 'identifier')]),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['name_primary'], name='deqar_progr_name_pr_5cac96_idx'),
        ),
    ]
