# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0002_auto_20171113_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('nqf_level', models.CharField(choices=[('level 6', 'level 6'), ('level 7', 'level 7'), ('level 8', 'level 8')], max_length=10)),
                ('countries', models.ManyToManyField(to='lists.Country')),
                ('qf_ehea_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lists.QFEHEALevel')),
            ],
            options={
                'db_table': 'eqar_programmes',
            },
        ),
        migrations.CreateModel(
            name='ProgrammeNames',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('name_is_english', models.BooleanField(default=False)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.Programme')),
            ],
            options={
                'db_table': 'eqar_programme_names',
            },
        ),
    ]
