# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nqf_level', models.CharField(blank=True, max_length=10)),
                ('countries', models.ManyToManyField(to='lists.Country')),
                ('qf_ehea_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.QFEHEALevel')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report')),
            ],
            options={
                'db_table': 'eqar_programmes',
            },
        ),
        migrations.CreateModel(
            name='ProgrammeNames',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('name_is_english', models.BooleanField(default=False)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.Programme')),
            ],
            options={
                'db_table': 'eqar_programme_names',
            },
        ),
    ]
