# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programmeidentifier',
            unique_together=set([('programme', 'agency', 'resource')]),
        ),
    ]
