# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report'),
        ),
    ]
