# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_auto_20180205_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='nqf_level',
            field=models.CharField(blank=True, choices=[('level 6', 'level 6'), ('level 7', 'level 7'), ('level 8', 'level 8')], max_length=10),
        ),
    ]
