# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0003_auto_20171126_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='qualification',
        ),
        migrations.AddField(
            model_name='programmenames',
            name='qualification',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
