# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0004_auto_20180214_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='countries',
            field=models.ManyToManyField(blank=True, to='countries.Country'),
        ),
    ]
