# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0005_auto_20180221_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='name_primary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='programmename',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='programmename',
            name='qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
