# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-19 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0006_auto_20180228_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='nqf_level',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
