# Generated by Django 2.0.8 on 2019-01-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0009_auto_20190131_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmeidentifier',
            name='resource',
            field=models.CharField(blank=True, default='local identifier', max_length=200),
        ),
    ]
