# Generated by Django 2.1.5 on 2019-03-01 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0010_auto_20190131_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmename',
            options={'ordering': ('-name_is_primary', 'name')},
        ),
    ]
