# Generated by Django 2.0.13 on 2019-05-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0011_auto_20190301_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programme',
            options={'ordering': ['id', 'report'], 'verbose_name': 'Programmme'},
        ),
        migrations.AlterModelOptions(
            name='programmeidentifier',
            options={'verbose_name': 'Programme Identifier'},
        ),
        migrations.AlterModelOptions(
            name='programmename',
            options={'ordering': ('-name_is_primary', 'name'), 'verbose_name': 'Programme Name'},
        ),
    ]
