# Generated by Django 2.2.28 on 2023-08-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0013_auto_20230807_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programme',
            old_name='assessment',
            new_name='assessment_certification',
        ),
        migrations.RenameField(
            model_name='programme',
            old_name='isced',
            new_name='field_study',
        ),
        migrations.RenameField(
            model_name='programme',
            old_name='ects_credit',
            new_name='workload_ects',
        ),
        migrations.RenameField(
            model_name='programmelearningoutcome',
            old_name='learning_outcome',
            new_name='learning_outcome_esco',
        ),
        migrations.AddField(
            model_name='programme',
            name='learning_outcome_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='programmelearningoutcome',
            unique_together={('programme', 'learning_outcome_esco')},
        ),
        migrations.RemoveField(
            model_name='programmelearningoutcome',
            name='learning_outcome_description',
        ),
    ]
