# Generated by Django 2.2.28 on 2023-08-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0014_auto_20230807_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='workload_ects',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
