# Generated by Django 2.2.28 on 2023-08-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0015_auto_20230808_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='degree_outcome',
        ),
    ]
