# Generated by Django 2.2.28 on 2023-08-31 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0018_auto_20230822_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='degree_outcome',
        ),
        migrations.AddField(
            model_name='programme',
            name='degree_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.DegreeOutcome'),
        ),
    ]
