# Generated by Django 2.2.28 on 2023-10-28 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0019_auto_20230831_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='degree_outcome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lists.DegreeOutcome'),
        ),
    ]
