# Generated by Django 2.2.28 on 2023-11-07 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0020_auto_20231107_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='degree_outcome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lists.DegreeOutcome'),
        ),
    ]
