# Generated by Django 4.2.19 on 2025-11-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0030_filter_by_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmename',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programmename',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
