# Generated by Django 4.2.19 on 2026-07-06 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0032_meili_report_id_filterable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmelearningoutcome',
            options={'ordering': ('id',), 'verbose_name': 'Programme Learning Outcome'},
        ),
    ]
