# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iso_3166_alpha2', models.CharField(max_length=2)),
                ('iso_3166_alpha3', models.CharField(max_length=3)),
                ('name_english', models.CharField(max_length=100, unique=True)),
                ('ehea_is_member', models.BooleanField(default=False)),
                ('eqar_govermental_member_start', models.DateField(blank=True, null=True)),
                ('qa_requirement', models.CharField(blank=True, max_length=200)),
                ('qa_requirement_notes', models.TextField(blank=True)),
                ('external_QAA_is_permitted', models.BooleanField(default=False)),
                ('eligibility', models.TextField(blank=True)),
                ('conditions', models.CharField(blank=True, max_length=200)),
                ('recognition', models.CharField(blank=True, max_length=200)),
                ('external_QAA_permitted_note', models.TextField(blank=True)),
                ('european_approach_is_permitted', models.BooleanField(default=False)),
                ('european_approach_note', models.TextField(blank=True)),
                ('general_note', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'deqar_counties',
            },
        ),
        migrations.CreateModel(
            name='CountryHistoricalField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'deqar_country_historical_fields',
            },
        ),
        migrations.CreateModel(
            name='CountryQAARegulation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regulation', models.CharField(blank=True, max_length=200)),
                ('regulation_url', models.URLField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country')),
            ],
            options={
                'db_table': 'deqar_country_qaa_regulations',
            },
        ),
        migrations.CreateModel(
            name='CountryQARequirementType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qa_requirement_type', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'deqar_country_qa_requirement_types',
            },
        ),
        migrations.CreateModel(
            name='InstitutionHistoricalData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.CountryHistoricalField')),
            ],
            options={
                'db_table': 'deqar_country_historical_data',
            },
        ),
        migrations.AddField(
            model_name='country',
            name='qa_requirement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.CountryQARequirementType'),
        ),
    ]
