# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 15:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iso_3166_alpha2', models.CharField(max_length=2)),
                ('iso_3166_alpha3', models.CharField(max_length=3)),
                ('name_english', models.CharField(max_length=100, unique=True)),
                ('ehea_is_member', models.BooleanField(default=False)),
                ('eqar_governmental_member_start', models.DateField(blank=True, null=True)),
                ('qa_requirement_note', models.TextField(blank=True)),
                ('external_QAA_note', models.TextField(blank=True, null=True)),
                ('eligibility', models.TextField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('recognition', models.TextField(blank=True, null=True)),
                ('european_approach_note', models.TextField(blank=True, null=True)),
                ('general_note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'deqar_countries',
                'ordering': ('name_english',),
            },
        ),
        migrations.CreateModel(
            name='CountryHistoricalData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('value', models.CharField(max_length=200)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deqar_country_historical_data',
            },
        ),
        migrations.CreateModel(
            name='CountryHistoricalField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'deqar_country_historical_fields',
            },
        ),
        migrations.CreateModel(
            name='CountryQAARegulation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regulation', models.CharField(blank=True, max_length=200)),
                ('regulation_url', models.URLField(blank=True)),
                ('regulation_valid_from', models.DateField(default=datetime.date.today)),
                ('regulation_valid_to', models.DateField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country')),
            ],
            options={
                'db_table': 'deqar_country_qaa_regulations',
            },
        ),
        migrations.CreateModel(
            name='CountryQARequirement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qa_requirement', models.CharField(max_length=200)),
                ('qa_requirement_note', models.TextField(blank=True)),
                ('requirement_valid_from', models.DateField(default=datetime.date.today)),
                ('requirement_valid_to', models.DateField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country')),
            ],
            options={
                'db_table': 'deqar_country_qa_requirements',
            },
        ),
        migrations.CreateModel(
            name='CountryQARequirementType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qa_requirement_type', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'deqar_country_qa_requirement_types',
            },
        ),
        migrations.AddField(
            model_name='countryqarequirement',
            name='qa_requirement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.CountryQARequirementType'),
        ),
        migrations.AddIndex(
            model_name='countryhistoricalfield',
            index=models.Index(fields=['field'], name='deqar_count_field_64c405_idx'),
        ),
        migrations.AddField(
            model_name='countryhistoricaldata',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country'),
        ),
        migrations.AddField(
            model_name='countryhistoricaldata',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.CountryHistoricalField'),
        ),
        migrations.AddField(
            model_name='country',
            name='european_approach_is_permitted',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='country_european_approach', to='lists.PermissionType'),
        ),
        migrations.AddField(
            model_name='country',
            name='external_QAA_is_permitted',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='country_external_qaa', to='lists.PermissionType'),
        ),
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lists.Flag'),
        ),
        migrations.AddIndex(
            model_name='countryqarequirement',
            index=models.Index(fields=['requirement_valid_to'], name='deqar_count_require_ee05e7_idx'),
        ),
        migrations.AddIndex(
            model_name='countryqaaregulation',
            index=models.Index(fields=['regulation_valid_to'], name='deqar_count_regulat_b20869_idx'),
        ),
        migrations.AddIndex(
            model_name='countryhistoricaldata',
            index=models.Index(fields=['valid_to'], name='deqar_count_valid_t_dd0e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['name_english'], name='deqar_count_name_en_172f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['ehea_is_member'], name='deqar_count_ehea_is_9617a8_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['eqar_governmental_member_start'], name='deqar_count_eqar_go_a43230_idx'),
        ),
    ]
