# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstitutionHistoricalData',
            new_name='CountryHistoricalData',
        ),
    ]
