# Generated by Django 2.1 on 2018-08-25 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_flag_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='european_approach_is_permitted',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='country_european_approach', to='lists.PermissionType'),
        ),
        migrations.AlterField(
            model_name='country',
            name='external_QAA_is_permitted',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='country_external_qaa', to='lists.PermissionType'),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lists.Flag'),
        ),
    ]
