# Generated by Django 2.0.13 on 2019-05-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_auto_20180825_0058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countryhistoricaldata',
            options={'verbose_name': 'Country Historical Data'},
        ),
        migrations.AlterModelOptions(
            name='countryhistoricalfield',
            options={'verbose_name': 'Country Historical Field'},
        ),
        migrations.AlterModelOptions(
            name='countryqaaregulation',
            options={'verbose_name': 'Country QAA Regulation'},
        ),
        migrations.AlterModelOptions(
            name='countryqarequirement',
            options={'verbose_name': 'Country QA Requirement'},
        ),
        migrations.AlterModelOptions(
            name='countryqarequirementtype',
            options={'verbose_name': 'Country QA Requirement Type'},
        ),
    ]
