# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_auto_20180107_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name_english',), 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
    ]
