# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_auto_20180108_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryQARequirement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qa_requirement', models.CharField(blank=True, max_length=200)),
                ('qa_requirement_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='qa_requirement',
        ),
        migrations.RemoveField(
            model_name='country',
            name='qa_requirement_type',
        ),
        migrations.AddField(
            model_name='countryqarequirement',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country'),
        ),
        migrations.AddField(
            model_name='countryqarequirement',
            name='qa_requirement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.CountryQARequirementType'),
        ),
    ]
