# Generated by Django 2.0.13 on 2019-09-08 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20190509_2012'),
        ('countries', '0004_auto_20190509_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='ehea_key_commitment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='country_ehea_key_commitment', to='lists.PermissionType'),
        ),
        migrations.AddField(
            model_name='country',
            name='has_full_institution_list',
            field=models.BooleanField(default=False),
        ),
    ]
