# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_auto_20180110_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='qa_requirement_notes',
            new_name='qa_requirement_note',
        ),
        migrations.RenameField(
            model_name='countryqarequirement',
            old_name='qa_requirement_notes',
            new_name='qa_requirement_note',
        ),
    ]
