# Generated by Django 2.2.28 on 2022-12-27 22:17

from django.db import migrations, models
import django.db.models.deletion
import eqar_backend.fields


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_auto_20200717_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='eu_controlled_vocab_atu',
            field=eqar_backend.fields.CharNullField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='eu_controlled_vocab_country',
            field=eqar_backend.fields.CharNullField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='generic_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='orgreg_eu_2_letter_code',
            field=eqar_backend.fields.CharNullField(blank=True, max_length=2, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='orgreg_subcountry_label',
            field=eqar_backend.fields.CharNullField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='countries.Country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_3166_alpha2',
            field=eqar_backend.fields.CharNullField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_3166_alpha3',
            field=eqar_backend.fields.CharNullField(max_length=3, unique=True),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['iso_3166_alpha2'], name='deqar_count_iso_316_5a9e4f_idx'),
        ),
    ]
