# Generated by Django 2.2.28 on 2022-12-27 22:22

from django.db import migrations


def set_country_values(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Country = apps.get_model('countries', 'Country')
    for country in Country.objects.all():
        # Set OrgReg EU 2-letter code
        if country.iso_3166_alpha2 == 'GB':
            country.orgreg_eu_2_letter_code = 'UK'
        else:
            country.orgreg_eu_2_letter_code = country.iso_3166_alpha2

        # Set EU Controlled Vocabulary for country concept scheme
        country.eu_controlled_vocab_country = "http://publications.europa.eu/resource/authority/country/%s" % \
                                              country.iso_3166_alpha3.upper()

        # Set EU Controlled Vocabulary for administrative territorial unit
        country.eu_controlled_vocab_atu = "http://publications.europa.eu/resource/authority/atu/%s" % \
                                          country.iso_3166_alpha3.upper()
        country.save()


class Migration(migrations.Migration):
    dependencies = [
        ('countries', '0007_auto_20221227_2217'),
    ]

    operations = [
        migrations.RunPython(set_country_values),
    ]
