# Generated by Django 2.2.28 on 2023-01-09 20:09

from django.db import migrations
import eqar_backend.fields


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0008_auto_20221227_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso_3166_alpha3',
            field=eqar_backend.fields.char_null_field.CharNullField(blank=True, max_length=3, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='orgreg_subcountry_label',
            field=eqar_backend.fields.char_null_field.CharNullField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='country',
            unique_together={('parent', 'orgreg_subcountry_label')},
        ),
    ]
