# Generated by Django 2.2.28 on 2023-01-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0009_auto_20230109_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='eu_controlled_vocab_atu',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='eu_controlled_vocab_country',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_3166_alpha2',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_3166_alpha3',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='orgreg_eu_2_letter_code',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='orgreg_subcountry_label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
