# Generated by Django 2.2.28 on 2023-01-09 21:56

from django.db import migrations, models
import eqar_backend.fields


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0010_auto_20230109_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='orgreg_subcountry_label',
            field=eqar_backend.fields.CharNullField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='country',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(fields=('parent', 'orgreg_subcountry_label'), name='orgreg_subcountry_unique'),
        ),
    ]
