# Generated by Django 4.2.19 on 2026-05-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0011_auto_20230109_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryhistoricaldata',
            name='value',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='countryqaaregulation',
            name='regulation',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='countryqaaregulation',
            name='regulation_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='countryqarequirement',
            name='qa_requirement',
            field=models.CharField(max_length=500),
        ),
    ]
