# Generated by Django 4.2.19 on 2025-11-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deqarprofile',
            options={'ordering': ['user__username']},
        ),
    ]
