# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0002_auto_20171113_2146'),
        ('agencies', '0002_auto_20171113_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agency_identifier', models.CharField(blank=True, max_length=50, null=True)),
                ('report_name', models.CharField(max_length=100)),
                ('report_type', models.CharField(max_length=50)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency')),
                ('agency_esg_activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agencies.AgencyESGActivities')),
            ],
            options={
                'db_table': 'eqar_reports',
            },
        ),
        migrations.CreateModel(
            name='ReportDecision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'eqar_report_decision',
            },
        ),
        migrations.CreateModel(
            name='ReportStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'eqar_report_statuses',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.ReportDecision'),
        ),
        migrations.AddField(
            model_name='report',
            name='institutions',
            field=models.ManyToManyField(to='institutions.Institution'),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.ReportStatus'),
        ),
    ]
