# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
        ('institutions', '0001_initial'),
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('local_identifier', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=300)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency')),
                ('agency_esg_activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agencies.AgencyESGActivity')),
            ],
            options={
                'db_table': 'deqar_reports',
            },
        ),
        migrations.CreateModel(
            name='ReportDecision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'deqar_report_decision',
            },
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_display_name', models.CharField(max_length=100)),
                ('file_original_location', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='')),
                ('languages', models.ManyToManyField(to='lists.Language')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report')),
            ],
            options={
                'db_table': 'deqar_report_files',
            },
        ),
        migrations.CreateModel(
            name='ReportLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link_display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report')),
            ],
            options={
                'db_table': 'deqar_report_links',
            },
        ),
        migrations.CreateModel(
            name='ReportStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'deqar_report_statuses',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.ReportDecision'),
        ),
        migrations.AddField(
            model_name='report',
            name='flag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lists.Flag'),
        ),
        migrations.AddField(
            model_name='report',
            name='institutions',
            field=models.ManyToManyField(related_name='reports', to='institutions.Institution'),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.ReportStatus'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['valid_from'], name='deqar_repor_valid_f_91a18f_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['valid_to'], name='deqar_repor_valid_t_9bf828_idx'),
        ),
    ]
