# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20180107_1722'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_display_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('languages', models.ManyToManyField(to='lists.Language')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report')),
            ],
            options={
                'db_table': 'deqar_report_files',
            },
        ),
    ]
