# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-11 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_auto_20180208_1342'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set([('agency', 'local_identifier')]),
        ),
    ]
