# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-19 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20180305_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='file_original_location',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
