# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-25 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20180319_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='local_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
