# Generated by Django 2.1 on 2018-08-25 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20180625_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='flag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lists.Flag'),
        ),
    ]
