# Generated by Django 2.0.8 on 2019-01-31 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20180825_0058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportfile',
            options={'ordering': ['id', 'report']},
        ),
    ]
