# Generated by Django 2.1.5 on 2019-02-24 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0002_auto_20190223_1739'),
        ('reports', '0013_auto_20190131_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFlag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flag_message', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('removed_by_eqar', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lists.Flag')),
            ],
            options={
                'db_table': 'deqar_report_flags',
                'ordering': ['id', 'flag__id'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportflag',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report'),
        ),
        migrations.AlterUniqueTogether(
            name='reportflag',
            unique_together={('report', 'flag_message')},
        ),
    ]
