# Generated by Django 2.1.5 on 2019-03-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20190224_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='internal_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='other_comment',
            field=models.TextField(blank=True),
        ),
    ]
