# Generated by Django 2.0.13 on 2019-04-29 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0015_auto_20190306_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportUpdateLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_log_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deqar_report_update_log',
            },
        ),
    ]
