# Generated by Django 2.0.13 on 2019-05-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_reportupdatelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Report'},
        ),
        migrations.AlterModelOptions(
            name='reportdecision',
            options={'verbose_name': 'Report Decision'},
        ),
        migrations.AlterModelOptions(
            name='reportfile',
            options={'ordering': ['id', 'report'], 'verbose_name': 'Report File'},
        ),
        migrations.AlterModelOptions(
            name='reportflag',
            options={'ordering': ['id', 'flag__id'], 'verbose_name': 'Report Flag'},
        ),
        migrations.AlterModelOptions(
            name='reportlink',
            options={'verbose_name': 'Report Link'},
        ),
        migrations.AlterModelOptions(
            name='reportstatus',
            options={'verbose_name': 'Report Status'},
        ),
        migrations.AlterModelOptions(
            name='reportupdatelog',
            options={'verbose_name': 'Report Update Log'},
        ),
    ]
