# Generated by Django 2.0.13 on 2019-11-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_auto_20190509_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='internal_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='other_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
