# Generated by Django 2.2.13 on 2020-08-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_auto_20191114_0746'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
    ]
