# Generated by Django 2.2.13 on 2020-08-13 19:46

from django.db import migrations
import eqar_backend.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0012_auto_20200717_1742'),
        ('reports', '0019_auto_20200811_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='local_identifier',
            field=eqar_backend.fields.CharNullField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('agency', 'local_identifier')},
        ),
    ]
