# Generated by Django 2.0.13 on 2020-11-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_auto_20200813_1946'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
    ]
