# Generated by Django 2.2.24 on 2021-08-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_auto_20201104_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
