# Generated by Django 2.2.24 on 2021-09-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0013_auto_20210905_2010'),
        ('reports', '0022_report_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='contributing_agencies',
            field=models.ManyToManyField(blank=True, related_name='co_authored_reports', to='agencies.Agency'),
        ),
    ]
