# Generated by Django 2.2.28 on 2023-08-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_report_contributing_agencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='mc_as_part_of_accreditation',
            field=models.BooleanField(default=False),
        ),
    ]
