# Generated by Django 2.2.28 on 2023-08-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_report_mc_as_part_of_accreditation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='mc_as_part_of_accreditation',
            new_name='micro_credentials_covered',
        ),
    ]
