# Generated by Django 2.2.28 on 2023-11-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_auto_20230807_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='micro_credentials_covered',
        ),
    ]
