# Generated by Django 2.2.28 on 2025-02-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0035_auto_20240207_2139'),
        ('reports', '0026_remove_report_micro_credentials_covered'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='platforms',
            field=models.ManyToManyField(related_name='related_reports', to='institutions.Institution'),
        ),
    ]
