# Generated by Django 2.2.28 on 2025-03-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_report_platforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='related_reports', to='institutions.Institution'),
        ),
    ]
