# Generated by Django 2.2.28 on 2025-01-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_configure_meilisearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfile',
            name='file_checksum',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
