# Generated by Django 2.2.28 on 2025-01-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0013_auto_20210905_2010'),
        ('reports', '0028_reportfile_file_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='agency_esg_activities',
            field=models.ManyToManyField(related_name='reports', to='agencies.AgencyESGActivity'),
        ),
    ]
