# Generated by Django 2.2.28 on 2025-01-03 09:02

from django.db import migrations, models

def populate_agency_esg_activities(apps, schema_editor):
    Report = apps.get_model("reports", "Report")
    for report in Report.objects.all():
        report.agency_esg_activities.add(report.agency_esg_activity)
        report.save()

class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0029_report_agency_esg_activities'),
    ]

    operations = [
        migrations.RunPython(populate_agency_esg_activities, reverse_code=migrations.RunPython.noop),
    ]
