# Generated by Django 2.2.28 on 2025-01-03 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0030_populate_agency_esg_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='agency_esg_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agencies.AgencyESGActivity'),
        ),
    ]
