# Generated by Django 4.2.19 on 2025-03-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0037_delete_institutioneterrecord'),
        ('reports', '0032_configure_meilisearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='platforms',
            field=models.ManyToManyField(related_name='related_reports', to='institutions.institution'),
        ),
    ]
