# Generated by Django 4.2.19 on 2025-03-25 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0028_auto_20250312_1859'),
        ('reports', '0032_configure_meilisearch'),
    ]

    operations = [
    ]
