# Generated by Django 4.2.19 on 2025-03-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0037_delete_institutioneterrecord'),
        ('reports', '0033_report_platforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='related_reports', to='institutions.institution'),
        ),
    ]
