# Generated by Django 4.2.19 on 2025-03-25 18:11

from django.db import migrations
from django.conf import settings

from eqar_backend.meilisearch import MeiliClient

def configure_index(apps, schema_editor):
    if hasattr(settings, "MEILI_API_URL"):
        meili = MeiliClient()
        meili.wait_for(meili.update_settings(meili.INDEX_REPORTS, {
            'filterableAttributes': [
                'agency.id',
                'contributing_agencies.id',
                'agency_esg_activities.id',
                'agency_esg_activities.group_id',
                'agency_esg_activities.type',
                'crossborder',
                'decision',
                'status',
                'valid_from',
                'valid_to_calculated',
                'created_at',
                'updated_at',
                'report_files.languages',
                'institutions.id',
                'institutions.locations.country.id',
                'institutions.locations.country.iso_3166_alpha2',
                'institutions.locations.country.iso_3166_alpha3',
                'institutions.locations.country.ehea_is_member',
                'platforms.id',
                'platforms.locations.country.id',
                'platforms.locations.country.iso_3166_alpha2',
                'platforms.locations.country.iso_3166_alpha3',
                'platforms.locations.country.ehea_is_member',
                'programmes.degree_outcome',
                'programmes.qf_ehea_level',
                'programmes.programme_type',
                'programmes.workload_ects',
                'other_provider_covered',
                'flag',
            ],
        }))


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0034_update_meili_platforms'),
    ]

    operations = [
        migrations.RunPython(configure_index, reverse_code=migrations.RunPython.noop),
    ]

