# Generated by Django 4.2.19 on 2025-04-06 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0036_remove_report_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='agency_esg_activity',
        ),
    ]
