# Generated by Django 4.2.19 on 2025-06-29 21:15

from django.db import migrations
from django.conf import settings

from eqar_backend.meilisearch import MeiliClient

def configure_index(apps, schema_editor):
    if hasattr(settings, "MEILI_API_URL"):
        meili = MeiliClient()
        meili.wait_for(meili.update_settings(meili.INDEX_REPORTS, {
            'faceting': {
                'maxValuesPerFacet': 1000,
            },
        }))



class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0037_remove_report_agency_esg_activity'),
    ]

    operations = [
        migrations.RunPython(configure_index, reverse_code=migrations.RunPython.noop),
    ]
