# Generated by Django 4.2.19 on 2026-04-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0038_update_meili_facets'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfile',
            name='download_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], max_length=20),
        ),
    ]
