# Generated by Django 4.2.19 on 2026-05-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0039_reportfile_download_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='download_status',
            field=models.CharField(
                blank=True,
                choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')],
                default='pending',
                max_length=20
            ),
        ),
    ]
