# Generated by Django 4.2.19 on 2026-07-06 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0040_reportfile_download_status_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportlink',
            options={'ordering': ('id',), 'verbose_name': 'Report Link'},
        ),
    ]
