# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 14:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deqar_id', models.IntegerField()),
                ('name_primary', models.CharField(blank=True, max_length=200)),
                ('acronym_primary', models.CharField(blank=True, max_length=20)),
                ('contact_person', models.CharField(max_length=150)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('website_link', models.URLField(max_length=100)),
                ('logo', models.FileField(blank=True, null=True, upload_to='')),
                ('specialisation_note', models.TextField(blank=True)),
                ('reports_link', models.URLField(blank=True, null=True)),
                ('description_note', models.TextField()),
                ('registration_start', models.DateField()),
                ('registration_valid_to', models.DateField()),
                ('registration_note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
                'db_table': 'deqar_agencies',
                'ordering': ('acronym_primary', 'name_primary'),
            },
        ),
        migrations.CreateModel(
            name='AgencyActivityType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'deqar_agency_activity_types',
            },
        ),
        migrations.CreateModel(
            name='AgencyEmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'deqar_agency_emails',
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='AgencyEQARDecision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('decision_date', models.DateField()),
                ('decision_file', models.FileField(upload_to='')),
                ('decision_file_extra', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'db_table': 'deqar_agency_eqar_decisions',
            },
        ),
        migrations.CreateModel(
            name='AgencyESGActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=500)),
                ('activity_local_identifier', models.CharField(blank=True, max_length=20)),
                ('activity_description', models.CharField(blank=True, max_length=300)),
                ('reports_link', models.URLField(blank=True, null=True)),
                ('activity_valid_from', models.DateField(default=datetime.date.today)),
                ('activity_valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deqar_agency_esg_activities',
                'ordering': ('agency', 'activity'),
            },
        ),
        migrations.CreateModel(
            name='AgencyFocusCountry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_is_official', models.BooleanField(default=False)),
                ('country_is_crossborder', models.BooleanField(default=False)),
                ('country_valid_from', models.DateField(auto_now_add=True)),
                ('country_valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deqar_agency_focus_countries',
                'ordering': ('country__name_english',),
            },
        ),
        migrations.CreateModel(
            name='AgencyGeographicalFocus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('focus', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'deqar_agency_geographical_focuses',
            },
        ),
        migrations.CreateModel(
            name='AgencyHistoricalData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('value', models.CharField(max_length=200)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deqar_agency_historical_data',
            },
        ),
        migrations.CreateModel(
            name='AgencyHistoricalField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'deqar_agency_historical_fields',
            },
        ),
        migrations.CreateModel(
            name='AgencyMembership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('membership_valid_from', models.DateField(auto_now_add=True)),
                ('membership_valid_to', models.DateField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lists.Association')),
            ],
            options={
                'db_table': 'deqar_agency_memberships',
            },
        ),
        migrations.CreateModel(
            name='AgencyName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_note', models.TextField(blank=True)),
                ('name_valid_to', models.DateField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency')),
            ],
            options={
                'verbose_name': 'Agency Name',
                'verbose_name_plural': 'Agency Names',
                'db_table': 'deqar_agency_names',
            },
        ),
        migrations.CreateModel(
            name='AgencyNameVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('name_transliterated', models.CharField(blank=True, max_length=200)),
                ('name_is_primary', models.BooleanField(default=False)),
                ('acronym', models.CharField(blank=True, max_length=20)),
                ('acronym_transliterated', models.CharField(blank=True, max_length=20)),
                ('acronym_is_primary', models.BooleanField(default=False)),
                ('agency_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.AgencyName')),
            ],
            options={
                'db_table': 'deqar_agency_name_versions',
                'ordering': ('name_is_primary', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AgencyPhone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency')),
            ],
            options={
                'db_table': 'deqar_agency_phones',
            },
        ),
        migrations.CreateModel(
            name='AgencyProxy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proxy_from', models.DateField(auto_now_add=True)),
                ('proxy_to', models.DateField(blank=True, null=True)),
                ('allowed_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_agency', to='agencies.Agency')),
                ('submitting_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitting_agency', to='agencies.Agency')),
            ],
            options={
                'db_table': 'deqar_agency_agency_proxies',
            },
        ),
        migrations.CreateModel(
            name='AgencyRelationship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('date', models.DateField()),
                ('from_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_agencies', to='agencies.Agency')),
                ('to_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_agencies', to='agencies.Agency')),
            ],
            options={
                'db_table': 'deqar_agency_relationships',
            },
        ),
        migrations.CreateModel(
            name='SubmittingAgency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_agency', models.CharField(blank=True, max_length=200)),
                ('external_agency_acronym', models.CharField(blank=True, max_length=20)),
                ('registration_from', models.DateField(auto_now_add=True)),
                ('registration_to', models.DateField(blank=True, null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency')),
            ],
            options={
                'db_table': 'deqar_agency_submitting_agencies',
            },
        ),
        migrations.AddIndex(
            model_name='agencyhistoricalfield',
            index=models.Index(fields=['field'], name='deqar_agenc_field_324b36_idx'),
        ),
        migrations.AddField(
            model_name='agencyhistoricaldata',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency'),
        ),
        migrations.AddField(
            model_name='agencyhistoricaldata',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.AgencyHistoricalField'),
        ),
        migrations.AddField(
            model_name='agencyfocuscountry',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency'),
        ),
        migrations.AddField(
            model_name='agencyfocuscountry',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='countries.Country'),
        ),
        migrations.AddField(
            model_name='agencyesgactivity',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agencies.AgencyActivityType'),
        ),
        migrations.AddField(
            model_name='agencyesgactivity',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency'),
        ),
        migrations.AddField(
            model_name='agencyeqardecision',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency'),
        ),
        migrations.AddField(
            model_name='agencyeqardecision',
            name='decision_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.EQARDecisionType'),
        ),
        migrations.AddField(
            model_name='agencyemail',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency'),
        ),
        migrations.AddField(
            model_name='agency',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country'),
        ),
        migrations.AddField(
            model_name='agency',
            name='flag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lists.Flag'),
        ),
        migrations.AddField(
            model_name='agency',
            name='geographical_focus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agencies.AgencyGeographicalFocus'),
        ),
        migrations.AddField(
            model_name='agency',
            name='related_agencies',
            field=models.ManyToManyField(through='agencies.AgencyRelationship', to='agencies.Agency'),
        ),
        migrations.AlterUniqueTogether(
            name='agencyrelationship',
            unique_together=set([('from_agency', 'to_agency')]),
        ),
        migrations.AddIndex(
            model_name='agencyproxy',
            index=models.Index(fields=['proxy_to'], name='deqar_agenc_proxy_t_246e81_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agencyproxy',
            unique_together=set([('submitting_agency', 'allowed_agency')]),
        ),
        migrations.AlterUniqueTogether(
            name='agencyphone',
            unique_together=set([('agency', 'phone')]),
        ),
        migrations.AddIndex(
            model_name='agencyname',
            index=models.Index(fields=['name_valid_to'], name='deqar_agenc_name_va_229e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='agencymembership',
            index=models.Index(fields=['membership_valid_to'], name='deqar_agenc_members_ff6e92_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agencymembership',
            unique_together=set([('agency', 'association')]),
        ),
        migrations.AddIndex(
            model_name='agencyhistoricaldata',
            index=models.Index(fields=['valid_to'], name='deqar_agenc_valid_t_e782b1_idx'),
        ),
        migrations.AddIndex(
            model_name='agencyfocuscountry',
            index=models.Index(fields=['country_is_crossborder'], name='deqar_agenc_country_9ec885_idx'),
        ),
        migrations.AddIndex(
            model_name='agencyfocuscountry',
            index=models.Index(fields=['country_valid_to'], name='deqar_agenc_country_18e5d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agencyfocuscountry',
            unique_together=set([('agency', 'country')]),
        ),
        migrations.AddIndex(
            model_name='agencyesgactivity',
            index=models.Index(fields=['activity_valid_to'], name='deqar_agenc_activit_2f7e74_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agencyemail',
            unique_together=set([('agency', 'email')]),
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['name_primary'], name='deqar_agenc_name_pr_6a2304_idx'),
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['acronym_primary'], name='deqar_agenc_acronym_3f593b_idx'),
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['registration_valid_to'], name='deqar_agenc_registr_158af9_idx'),
        ),
    ]
