# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deqar_id', models.CharField(max_length=25)),
                ('name_primary', models.CharField(blank=True, max_length=200)),
                ('acronym_primary', models.CharField(blank=True, max_length=20)),
                ('contact_person', models.CharField(max_length=150)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('website_link', models.URLField(max_length=100)),
                ('logo', models.FileField(blank=True, null=True, upload_to='')),
                ('specialisation_note', models.TextField(blank=True)),
                ('reports_link', models.URLField(blank=True, null=True)),
                ('description_note', models.TextField()),
                ('registration_start', models.DateField()),
                ('registration_valid_to', models.DateField()),
                ('registration_note', models.TextField(blank=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.Country')),
            ],
            options={
                'db_table': 'deqar_agencies',
                'ordering': ('acronym_primary', 'name_primary'),
            },
        ),
        migrations.CreateModel(
            name='AgencyActivityType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'deqar_agency_activity_types',
            },
        ),
        migrations.CreateModel(
            name='AgencyEmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency')),
            ],
            options={
                'db_table': 'deqar_agency_emails',
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='AgencyEQARDecision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('decision_date', models.DateField()),
                ('decision_file', models.FileField(upload_to='')),
                ('decision_file_extra', models.FileField(blank=True, upload_to='')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency')),
                ('decision_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.EQARDecisionType')),
            ],
            options={
                'db_table': 'deqar_agency_eqar_decisions',
            },
        ),
        migrations.CreateModel(
            name='AgencyESGActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=200)),
                ('activity_local_identifier', models.CharField(blank=True, max_length=20)),
                ('activity_description', models.CharField(blank=True, max_length=300)),
                ('reports_link', models.URLField(blank=True, null=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agencies.AgencyActivityType')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency')),
            ],
            options={
                'db_table': 'deqar_agency_esg_activities',
            },
        ),
        migrations.CreateModel(
            name='AgencyFocusCountry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_is_official', models.BooleanField(default=False)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='countries.Country')),
            ],
            options={
                'db_table': 'deqar_agency_focus_countries',
                'ordering': ('country__name_english',),
            },
        ),
        migrations.CreateModel(
            name='AgencyGeographicalFocus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('focus', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'deqar_agency_geographical_focuses',
            },
        ),
        migrations.CreateModel(
            name='AgencyHistoricalData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency')),
            ],
            options={
                'db_table': 'deqar_agecy_historical_data',
            },
        ),
        migrations.CreateModel(
            name='AgencyHistoricalField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'deqar_agency_historical_fields',
            },
        ),
        migrations.CreateModel(
            name='AgencyMembership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lists.Association')),
            ],
            options={
                'db_table': 'deqar_agency_memberships',
            },
        ),
        migrations.CreateModel(
            name='AgencyName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_note', models.TextField(blank=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency')),
            ],
            options={
                'db_table': 'deqar_agency_names',
            },
        ),
        migrations.CreateModel(
            name='AgencyNameVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('name_transliterated', models.CharField(blank=True, max_length=200)),
                ('name_is_primary', models.BooleanField(default=False)),
                ('acronym', models.CharField(blank=True, max_length=20)),
                ('acronym_transliterated', models.CharField(blank=True, max_length=20)),
                ('acronym_is_primary', models.BooleanField(default=False)),
                ('agency_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.AgencyName')),
            ],
            options={
                'db_table': 'deqar_agency_name_versions',
                'ordering': ('name_is_primary', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AgencyPhone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency')),
            ],
            options={
                'db_table': 'deqar_agency_phones',
            },
        ),
        migrations.CreateModel(
            name='AgencyRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('date', models.DateField()),
                ('from_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_agencies', to='agencies.Agency')),
                ('to_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_agencies', to='agencies.Agency')),
            ],
            options={
                'db_table': 'deqar_agency_relationships',
            },
        ),
        migrations.AddField(
            model_name='agencyhistoricaldata',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.AgencyHistoricalField'),
        ),
        migrations.AddField(
            model_name='agency',
            name='geographical_focus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agencies.AgencyGeographicalFocus'),
        ),
        migrations.AddField(
            model_name='agency',
            name='related_agencies',
            field=models.ManyToManyField(through='agencies.AgencyRelationship', to='agencies.Agency'),
        ),
        migrations.AlterUniqueTogether(
            name='agencyrelationship',
            unique_together=set([('from_agency', 'to_agency')]),
        ),
        migrations.AlterUniqueTogether(
            name='agencyphone',
            unique_together=set([('agency', 'phone')]),
        ),
        migrations.AlterUniqueTogether(
            name='agencymembership',
            unique_together=set([('agency', 'association')]),
        ),
        migrations.AlterUniqueTogether(
            name='agencyfocuscountry',
            unique_together=set([('agency', 'country')]),
        ),
        migrations.AlterUniqueTogether(
            name='agencyemail',
            unique_together=set([('agency', 'email')]),
        ),
    ]
