# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyesgactivities',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agencies.AgencyActivityType'),
        ),
        migrations.AlterField(
            model_name='agencyfocuscountry',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lists.Country'),
        ),
        migrations.AlterField(
            model_name='agencylevels',
            name='qf_ehea_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lists.QFEHEALevel'),
        ),
        migrations.AlterField(
            model_name='agencylocationcountry',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lists.Country'),
        ),
        migrations.AlterField(
            model_name='agencymembership',
            name='associaton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lists.Association'),
        ),
    ]
