# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyactivitytype',
            name='type',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
