# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ('acronym_primary', 'name_primary'), 'verbose_name': 'Agency', 'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterModelOptions(
            name='agencyname',
            options={'verbose_name': 'Agency Name', 'verbose_name_plural': 'Agency Names'},
        ),
    ]
