# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_auto_20171113_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='address',
            field=models.TextField(default='Address'),
            preserve_default=False,
        ),
    ]
