# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_auto_20180107_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencyesgactivity',
            options={'ordering': ('agency', 'activity')},
        ),
        migrations.AlterField(
            model_name='agencyesgactivity',
            name='activity',
            field=models.CharField(max_length=300),
        ),
    ]
