# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_agency_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgencyESGActivities',
            new_name='AgencyESGActivity',
        ),
        migrations.RenameModel(
            old_name='AgencyLevels',
            new_name='AgencyLevel',
        ),
        migrations.RenameField(
            model_name='agencymembership',
            old_name='associaton',
            new_name='association',
        ),
    ]
