# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_auto_20180107_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyesgactivity',
            name='activity',
            field=models.CharField(max_length=500),
        ),
    ]
