# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-13 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_agency_flag_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyesgactivity',
            name='activity_local_identifier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
