# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-07 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_auto_20180413_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyeqardecision',
            name='decision_file',
            field=models.FileField(upload_to='EQAR/'),
        ),
        migrations.AlterField(
            model_name='agencyeqardecision',
            name='decision_file_extra',
            field=models.FileField(blank=True, upload_to='EQAR/'),
        ),
    ]
