# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20171129_2331'),
        ('agencies', '0004_auto_20171129_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyEQARDecision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('decision_date', models.DateField()),
                ('decision_file', models.FileField(upload_to='')),
                ('decision_file_extra', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'db_table': 'eqar_agency_eqar_decisions',
            },
        ),
        migrations.RemoveField(
            model_name='agencyeqarchange',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='agencyeqarrenewal',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='agencylevel',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='agencylevel',
            name='qf_ehea_level',
        ),
        migrations.RemoveField(
            model_name='agencylocationcountry',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='agencylocationcountry',
            name='country',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='enqua_membership',
        ),
        migrations.AddField(
            model_name='agency',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lists.Country'),
        ),
        migrations.DeleteModel(
            name='AgencyEQARChange',
        ),
        migrations.DeleteModel(
            name='AgencyEQARRenewal',
        ),
        migrations.DeleteModel(
            name='AgencyLevel',
        ),
        migrations.DeleteModel(
            name='AgencyLocationCountry',
        ),
        migrations.AddField(
            model_name='agencyeqardecision',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency'),
        ),
        migrations.AddField(
            model_name='agencyeqardecision',
            name='decision_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.EQARDecisionType'),
        ),
    ]
