# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20171129_2331'),
        ('agencies', '0005_auto_20171129_2331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgencyENQUAMembership',
        ),
        migrations.AddField(
            model_name='agency',
            name='acronym_primary',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='agency',
            name='name_primary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='agencyactivitytype',
            name='type',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='agencyfocus',
            name='focus',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='agencyemail',
            unique_together=set([('agency', 'email')]),
        ),
        migrations.AlterUniqueTogether(
            name='agencyfocuscountry',
            unique_together=set([('agency', 'country')]),
        ),
        migrations.AlterUniqueTogether(
            name='agencymembership',
            unique_together=set([('agency', 'association')]),
        ),
        migrations.AlterUniqueTogether(
            name='agencyphone',
            unique_together=set([('agency', 'phone')]),
        ),
    ]
