# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-31 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_auto_20180507_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyesgactivity',
            name='activity_display',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='agencyesgactivity',
            index=models.Index(fields=['activity_display'], name='deqar_agenc_activit_db73f7_idx'),
        ),
    ]
