# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-25 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0006_auto_20180731_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='is_registered',
            field=models.BooleanField(default=True),
        ),
    ]
