# Generated by Django 2.1 on 2018-08-25 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0007_agency_is_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='countries.Country'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='flag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lists.Flag'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='geographical_focus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agencies.AgencyGeographicalFocus'),
        ),
        migrations.AlterField(
            model_name='agencyeqardecision',
            name='decision_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lists.EQARDecisionType'),
        ),
    ]
