# Generated by Django 2.0.13 on 2019-05-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0008_auto_20180825_0058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencyactivitytype',
            options={'verbose_name': 'Agency Activity Type'},
        ),
        migrations.AlterModelOptions(
            name='agencyemail',
            options={'ordering': ('email',), 'verbose_name': 'Agency Email'},
        ),
        migrations.AlterModelOptions(
            name='agencyeqardecision',
            options={'verbose_name': 'Agency EQAR Decision'},
        ),
        migrations.AlterModelOptions(
            name='agencyesgactivity',
            options={'ordering': ('agency', 'activity'), 'verbose_name': 'Agency ESG Activity'},
        ),
        migrations.AlterModelOptions(
            name='agencyfocuscountry',
            options={'ordering': ('country__name_english',), 'verbose_name': 'Agency Focus Country'},
        ),
        migrations.AlterModelOptions(
            name='agencygeographicalfocus',
            options={'verbose_name': 'Agency Geographical Focus'},
        ),
        migrations.AlterModelOptions(
            name='agencyhistoricaldata',
            options={'verbose_name': 'Agency Historical Data'},
        ),
        migrations.AlterModelOptions(
            name='agencyhistoricalfield',
            options={'verbose_name': 'Agency Historical Field'},
        ),
        migrations.AlterModelOptions(
            name='agencymembership',
            options={'verbose_name': 'Agency Membership'},
        ),
        migrations.AlterModelOptions(
            name='agencynameversion',
            options={'ordering': ('name_is_primary', 'name'), 'verbose_name': 'Agency Name Version'},
        ),
        migrations.AlterModelOptions(
            name='agencyphone',
            options={'verbose_name': 'Agency Phone'},
        ),
        migrations.AlterModelOptions(
            name='agencyproxy',
            options={'verbose_name': 'Agency Proxy'},
        ),
        migrations.AlterModelOptions(
            name='agencyrelationship',
            options={'verbose_name': 'Agency Relationship'},
        ),
    ]
