# Generated by Django 2.0.13 on 2019-06-24 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0010_auto_20190619_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencynameversion',
            options={'ordering': ('-name_is_primary', 'name'), 'verbose_name': 'Agency Name Version'},
        ),
    ]
