# Generated by Django 2.2.24 on 2021-09-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0012_auto_20200717_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='registration_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='registration_valid_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
