# Generated by Django 4.2.19 on 2025-03-07 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0013_auto_20210905_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyActivityGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=500)),
                ('reports_link', models.URLField(blank=True, null=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agencies.agencyactivitytype')),
            ],
            options={
                'verbose_name': 'Agency ESG Activity Group',
                'db_table': 'deqar_agency_activity_group',
            },
        ),
        migrations.AddField(
            model_name='agencyesgactivity',
            name='activity_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agencies.agencyactivitygroup'),
        ),
    ]
