# Generated by Django 4.2.19 on 2025-03-09 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0015_create_activity_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyesgactivity',
            name='activity_type',
        ),
        migrations.AlterField(
            model_name='agencyesgactivity',
            name='activity_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agencies.agencyactivitygroup'),
        ),
    ]
