# Generated by Django 4.2.19 on 2025-03-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0016_remove_agencyesgactivity_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyesgactivity',
            name='activity',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
