# Generated by Django 4.2.19 on 2025-03-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0017_alter_agencyesgactivity_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencyactivitygroup',
            options={'verbose_name': 'ESG Activity Group'},
        ),
        migrations.AlterModelOptions(
            name='agencyesgactivity',
            options={'ordering': ('agency', 'activity'), 'verbose_name': 'ESG Activity', 'verbose_name_plural': 'ESG Activities'},
        ),
    ]
