# Generated by Django 4.2.19 on 2025-03-14 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0018_alter_agencyactivitygroup_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencyactivitygroup',
            options={'ordering': ('activity', 'activity_type'), 'verbose_name': 'ESG Activity Group'},
        ),
    ]
