# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('association', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'list_associations',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alpha2', models.CharField(blank=True, max_length=2)),
                ('alpha3', models.CharField(max_length=3)),
                ('country_name_en', models.CharField(max_length=100, unique=True)),
                ('qa_requirement_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'list_countries',
            },
        ),
        migrations.CreateModel(
            name='CountryQARequirement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qa_requirement', models.CharField(blank=True, max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lists.Country')),
            ],
        ),
        migrations.CreateModel(
            name='EQARDecisionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'list_eqar_decision_types',
            },
        ),
        migrations.CreateModel(
            name='ETEREntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eter_id', models.CharField(max_length=25)),
                ('institution_name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'list_eter_entities',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iso_639_1', models.CharField(max_length=10)),
                ('iso_639_2', models.CharField(blank=True, max_length=10)),
                ('language_name_en', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'list_languages',
            },
        ),
        migrations.CreateModel(
            name='QFEHEALevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('level', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'list_qf_ehea_levels',
            },
        ),
    ]
