# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('association', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'deqar_list_associations',
                'ordering': ('association',),
            },
        ),
        migrations.CreateModel(
            name='EQARDecisionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'EQAR Decision Type',
                'verbose_name_plural': 'EQAR Decision Types',
                'db_table': 'deqar_list_eqar_decision_types',
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flag', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Flag',
                'verbose_name_plural': 'Flags',
                'db_table': 'deqar_list_flags',
                'ordering': ('flag',),
            },
        ),
        migrations.CreateModel(
            name='IdentifierResource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resource', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Identifier Resource',
                'verbose_name_plural': 'Identifier Resources',
                'db_table': 'deqar_list_identifier_resources',
                'ordering': ('resource',),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iso_639_1', models.CharField(max_length=10)),
                ('iso_639_2', models.CharField(blank=True, max_length=10)),
                ('language_name_en', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'deqar_list_languages',
                'ordering': ('language_name_en',),
            },
        ),
        migrations.CreateModel(
            name='PermissionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Permission Type',
                'verbose_name_plural': 'Permission Types',
                'db_table': 'deqar_list_permission_types',
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='QFEHEALevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('level', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'QF-EHEA level',
                'verbose_name_plural': 'QF-EHEA levels',
                'db_table': 'deqar_list_qf_ehea_levels',
                'ordering': ('code',),
            },
        ),
    ]
