# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('association', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'deqar_list_associations',
            },
        ),
        migrations.CreateModel(
            name='EQARDecisionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'deqar_list_eqar_decision_types',
            },
        ),
        migrations.CreateModel(
            name='IdentifierResource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resource', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'deqar_list_identifier_resources',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iso_639_1', models.CharField(max_length=10)),
                ('iso_639_2', models.CharField(blank=True, max_length=10)),
                ('language_name_en', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'deqar_list_languages',
            },
        ),
        migrations.CreateModel(
            name='QFEHEALevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('level', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'deqar_list_qf_ehea_levels',
            },
        ),
    ]
