# Generated by Django 2.1.5 on 2019-02-23 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flag',
            options={'ordering': ('id', 'flag'), 'verbose_name': 'Flag', 'verbose_name_plural': 'Flags'},
        ),
    ]
