# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'ordering': ('association',)},
        ),
        migrations.AlterModelOptions(
            name='eqardecisiontype',
            options={'ordering': ('type',), 'verbose_name': 'EQAR Decision Types'},
        ),
        migrations.AlterModelOptions(
            name='identifierresource',
            options={'ordering': ('resource',), 'verbose_name': 'Identifier Resource', 'verbose_name_plural': 'Identifier Resources'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('language_name_en',)},
        ),
        migrations.AlterModelOptions(
            name='qfehealevel',
            options={'ordering': ('code',), 'verbose_name': 'QF-EHEA level', 'verbose_name_plural': 'QF-EHEA levels'},
        ),
    ]
