# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryqarequirement',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lists.Country'),
        ),
    ]
