# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20180107_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eqardecisiontype',
            options={'ordering': ('type',), 'verbose_name': 'EQAR Decision Type', 'verbose_name_plural': 'EQAR Decision Types'},
        ),
    ]
