# Generated by Django 2.0.13 on 2019-05-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20190223_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'ordering': ('association',), 'verbose_name': 'Association'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('language_name_en',), 'verbose_name': 'Language'},
        ),
    ]
