# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20171113_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='EQARDecisionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'list_eqar_decision_types',
            },
        ),
        migrations.AddField(
            model_name='qfehealevel',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
