# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20180107_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Permission Type',
                'verbose_name_plural': 'Permission Types',
                'db_table': 'deqar_list_permission_types',
                'ordering': ('type',),
            },
        ),
    ]
