# Generated by Django 2.2.28 on 2023-08-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20190509_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Assessment and Certification',
                'verbose_name_plural': 'Assessment and Certifications',
                'db_table': 'deqar_list_assessments',
                'ordering': ('assessment',),
            },
        ),
        migrations.CreateModel(
            name='DegreeOutcome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('outcome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Degree Outcome',
                'verbose_name_plural': 'Degree Outcomes',
                'db_table': 'deqar_list_degree_outcomes',
                'ordering': ('outcome',),
            },
        ),
        migrations.CreateModel(
            name='ECTSCredit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('credit', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ECTS Credit',
                'verbose_name_plural': 'ECTS Credits',
                'db_table': 'deqar_list_ects_credits',
                'ordering': ('credit',),
            },
        ),
    ]
