# Generated by Django 2.2.28 on 2023-08-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_assessment_degreeoutcome_ectscredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeoutcome',
            name='outcome',
            field=models.CharField(max_length=80),
        ),
    ]
