# Generated by Django 2.2.28 on 2023-08-08 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0015_auto_20230808_0516'),
        ('lists', '0005_auto_20230807_1652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ECTSCredit',
        ),
    ]
