# Generated by Django 2.2.28 on 2023-09-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_delete_ectscredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifierSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resource', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Identifier Source',
                'verbose_name_plural': 'Identifier Sources',
                'db_table': 'deqar_list_identifier_sources',
                'ordering': ('resource',),
            },
        ),
    ]
