# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 14:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0003_agency_flag_log'),
        ('reports', '0004_report_flag_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submitted_data', models.TextField(blank=True)),
                ('report_status', models.CharField(default='success', max_length=20)),
                ('report_warnings', models.TextField(blank=True)),
                ('institution_warnings', models.TextField(blank=True)),
                ('country_warnings', models.TextField(blank=True)),
                ('submission_date', models.DateField(default=datetime.date(2018, 2, 19))),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report')),
            ],
            options={
                'db_table': 'deqar_submission_log',
            },
        ),
    ]
