# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 14:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissionapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionlog',
            name='submission_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
