# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 17:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissionapi', '0003_submissionpackagelog_submissionreportlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionreportlog',
            name='submission_date',
        ),
        migrations.AlterField(
            model_name='submissionpackagelog',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
