# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submissionapi', '0006_submissionreportlog_submission_package_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionreportlog',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
