# Generated by Django 4.2.19 on 2025-04-06 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissionapi', '0007_submissionreportlog_submission_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmissionLog',
        ),
    ]
