# Generated by Django 4.2.19 on 2025-07-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissionapi', '0008_delete_submissionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionpackagelog',
            name='submission_errors',
            field=models.TextField(blank=True),
        ),
    ]
