# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
        ('countries', '0001_initial'),
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deqar_id', models.CharField(max_length=25)),
                ('name_primary', models.CharField(blank=True, max_length=200)),
                ('website_link', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'deqar_institutions',
                'ordering': ('name_primary',),
            },
        ),
        migrations.CreateModel(
            name='InstitutionCountry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='countries.Country')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution')),
            ],
            options={
                'db_table': 'deqar_institution_countries',
                'ordering': ('country__name_english',),
            },
        ),
        migrations.CreateModel(
            name='InstitutionETERRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eter_id', models.CharField(max_length=15)),
                ('national_identifier', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('name_english', models.CharField(blank=True, max_length=200)),
                ('acronym', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(max_length=3)),
                ('website', models.CharField(max_length=200)),
                ('ISCED_lowest', models.CharField(max_length=10)),
                ('ISCED_highest', models.CharField(max_length=10)),
                ('valid_from_year', models.DateField()),
                ('data_updated', models.DateField()),
                ('eter_link', models.URLField()),
            ],
            options={
                'db_table': 'deqar_institution_eter_records',
            },
        ),
        migrations.CreateModel(
            name='InstitutionHistoricalData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deqar_institution_historical_data',
            },
        ),
        migrations.CreateModel(
            name='InstitutionHistoricalField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'deqar_institution_historical_fields',
            },
        ),
        migrations.CreateModel(
            name='InstitutionIdentifier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=50)),
                ('resource', models.CharField(blank=True, max_length=200)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agencies.Agency')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution')),
            ],
            options={
                'db_table': 'deqar_institution_identifiers',
            },
        ),
        migrations.CreateModel(
            name='InstitutionName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_official', models.CharField(max_length=200)),
                ('name_official_transliterated', models.CharField(blank=True, max_length=200)),
                ('name_english', models.CharField(blank=True, max_length=200)),
                ('acronym', models.CharField(blank=True, max_length=20)),
                ('source_note', models.TextField(blank=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution')),
            ],
            options={
                'db_table': 'deqar_institution_names',
                'ordering': ('name_official', 'name_english'),
            },
        ),
        migrations.CreateModel(
            name='InstitutionNameVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('transliteration', models.CharField(blank=True, max_length=200)),
                ('institution_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.InstitutionName')),
            ],
            options={
                'db_table': 'deqar_institution_name_versions',
            },
        ),
        migrations.CreateModel(
            name='InstitutionNQFLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nqf_level', models.CharField(max_length=10)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution')),
            ],
            options={
                'db_table': 'deqar_institution_nqf_levels',
            },
        ),
        migrations.CreateModel(
            name='InstitutionQFEHEALevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution')),
                ('qf_ehea_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lists.QFEHEALevel')),
            ],
            options={
                'db_table': 'deqar_institution_qf_ehea_levels',
            },
        ),
        migrations.AddField(
            model_name='institutionhistoricaldata',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.InstitutionHistoricalField'),
        ),
        migrations.AddField(
            model_name='institutionhistoricaldata',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution'),
        ),
        migrations.AddField(
            model_name='institution',
            name='eter_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.InstitutionETERRecord'),
        ),
    ]
