# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyHistoricalData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eqar_institution_historical_data',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eqar_id', models.CharField(max_length=25)),
                ('name_primary', models.CharField(max_length=200)),
                ('website_link', models.CharField(max_length=150)),
                ('eter_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lists.ETEREntity')),
            ],
            options={
                'db_table': 'eqar_institutions',
            },
        ),
        migrations.CreateModel(
            name='InstitutionCountry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.Country')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution')),
            ],
            options={
                'db_table': 'eqar_institution_countries',
            },
        ),
        migrations.CreateModel(
            name='InstitutionHistoricalField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'eqar_institution_historical_fields',
            },
        ),
        migrations.CreateModel(
            name='InstitutionIdentifier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=50)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agencies.Agency')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution')),
            ],
            options={
                'db_table': 'eqar_institution_identifiers',
            },
        ),
        migrations.CreateModel(
            name='InstitutionName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_official', models.CharField(max_length=200)),
                ('name_official_transliterated', models.CharField(blank=True, max_length=200)),
                ('name_english', models.CharField(blank=True, max_length=200)),
                ('acronym', models.CharField(blank=True, max_length=20)),
                ('source_note', models.TextField(blank=True)),
                ('valid_to', models.DateField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution')),
            ],
            options={
                'db_table': 'eqar_institution_names',
            },
        ),
        migrations.CreateModel(
            name='InstitutionNameVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('transliteration', models.CharField(blank=True, max_length=200)),
                ('institution_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.InstitutionName')),
            ],
            options={
                'db_table': 'eqar_institution_name_versions',
            },
        ),
        migrations.CreateModel(
            name='InstitutionNQFLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nqf_level', models.CharField(choices=[('level 6', 'level 6'), ('level 7', 'level 7'), ('level 8', 'level 8')], max_length=10)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution')),
            ],
            options={
                'db_table': 'eqar_institution_nqf_levels',
            },
        ),
        migrations.CreateModel(
            name='InstitutionQFEHEALevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution')),
                ('qf_ehea_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.QFEHEALevel')),
            ],
            options={
                'db_table': 'eqar_institution_qf_ehea_levels',
            },
        ),
        migrations.CreateModel(
            name='InstitutionResource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resource', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'eqar_institution_resources',
            },
        ),
        migrations.AddField(
            model_name='institutionidentifier',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.InstitutionResource'),
        ),
        migrations.AddField(
            model_name='agencyhistoricaldata',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.InstitutionHistoricalField'),
        ),
        migrations.AddField(
            model_name='agencyhistoricaldata',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution'),
        ),
    ]
