# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 15:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('countries', '0001_initial'),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deqar_id', models.CharField(max_length=25)),
                ('name_primary', models.CharField(blank=True, max_length=200)),
                ('website_link', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'deqar_institutions',
                'ordering': ('name_primary',),
            },
        ),
        migrations.CreateModel(
            name='InstitutionCountry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('country_source', models.CharField(max_length=20)),
                ('country_source_note', models.CharField(blank=True, max_length=200)),
                ('country_valid_from', models.DateField(default=datetime.date.today)),
                ('country_valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deqar_institution_countries',
            },
        ),
        migrations.CreateModel(
            name='InstitutionETERRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eter_id', models.CharField(max_length=15)),
                ('national_identifier', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('name_english', models.CharField(blank=True, max_length=200)),
                ('acronym', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(max_length=3)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('website', models.CharField(max_length=200)),
                ('ISCED_lowest', models.CharField(max_length=10)),
                ('ISCED_highest', models.CharField(max_length=10)),
                ('valid_from_year', models.DateField()),
                ('data_updated', models.DateField()),
                ('eter_link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'ETER Record',
                'verbose_name_plural': 'ETER Records',
                'db_table': 'deqar_institution_eter_records',
            },
        ),
        migrations.CreateModel(
            name='InstitutionHistoricalData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('value', models.CharField(max_length=200)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deqar_institution_historical_data',
            },
        ),
        migrations.CreateModel(
            name='InstitutionHistoricalField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'deqar_institution_historical_fields',
            },
        ),
        migrations.CreateModel(
            name='InstitutionIdentifier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=50)),
                ('resource', models.CharField(blank=True, max_length=200)),
                ('identifier_valid_from', models.DateField(default=datetime.date.today)),
                ('identifier_valid_to', models.DateField(blank=True, null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agencies.Agency')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution')),
            ],
            options={
                'db_table': 'deqar_institution_identifiers',
            },
        ),
        migrations.CreateModel(
            name='InstitutionName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_official', models.CharField(max_length=200)),
                ('name_official_transliterated', models.CharField(blank=True, max_length=200)),
                ('name_english', models.CharField(blank=True, max_length=200)),
                ('acronym', models.CharField(blank=True, max_length=20)),
                ('name_source_note', models.TextField()),
                ('name_valid_to', models.DateField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution')),
            ],
            options={
                'verbose_name': 'Institution Name',
                'verbose_name_plural': 'Institution Names',
                'db_table': 'deqar_institution_names',
                'ordering': ('institution', 'name_official', 'name_english'),
            },
        ),
        migrations.CreateModel(
            name='InstitutionNameVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('transliteration', models.CharField(blank=True, max_length=200)),
                ('name_version_source', models.CharField(max_length=20)),
                ('name_version_source_note', models.CharField(blank=True, max_length=200)),
                ('institution_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.InstitutionName')),
            ],
            options={
                'db_table': 'deqar_institution_name_versions',
            },
        ),
        migrations.CreateModel(
            name='InstitutionNQFLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nqf_level', models.CharField(max_length=10)),
                ('nqf_level_source', models.CharField(max_length=20)),
                ('nqf_level_source_note', models.CharField(blank=True, max_length=200)),
                ('nqf_level_valid_from', models.DateField(default=datetime.date.today)),
                ('nqf_level_valid_to', models.DateField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution')),
            ],
            options={
                'db_table': 'deqar_institution_nqf_levels',
            },
        ),
        migrations.CreateModel(
            name='InstitutionQFEHEALevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qf_ehea_level_source', models.CharField(max_length=20)),
                ('qf_ehea_level_source_note', models.CharField(blank=True, max_length=200)),
                ('qf_ehea_level_valid_from', models.DateField(default=datetime.date.today)),
                ('qf_ehea_level_valid_to', models.DateField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution')),
                ('qf_ehea_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lists.QFEHEALevel')),
            ],
            options={
                'db_table': 'deqar_institution_qf_ehea_levels',
            },
        ),
        migrations.AddIndex(
            model_name='institutionhistoricalfield',
            index=models.Index(fields=['field'], name='deqar_insti_field_530321_idx'),
        ),
        migrations.AddField(
            model_name='institutionhistoricaldata',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.InstitutionHistoricalField'),
        ),
        migrations.AddField(
            model_name='institutionhistoricaldata',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution'),
        ),
        migrations.AddField(
            model_name='institutioncountry',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='countries.Country'),
        ),
        migrations.AddField(
            model_name='institutioncountry',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution'),
        ),
        migrations.AddField(
            model_name='institution',
            name='eter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.InstitutionETERRecord'),
        ),
        migrations.AddField(
            model_name='institution',
            name='flag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lists.Flag'),
        ),
        migrations.AddIndex(
            model_name='institutionqfehealevel',
            index=models.Index(fields=['qf_ehea_level_valid_to'], name='deqar_insti_qf_ehea_765b40_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionnqflevel',
            index=models.Index(fields=['nqf_level_valid_to'], name='deqar_insti_nqf_lev_f88f71_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionnameversion',
            index=models.Index(fields=['name'], name='deqar_insti_name_b13205_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionnameversion',
            index=models.Index(fields=['transliteration'], name='deqar_insti_transli_653212_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionname',
            index=models.Index(fields=['name_official'], name='deqar_insti_name_of_da766e_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionname',
            index=models.Index(fields=['name_official_transliterated'], name='deqar_insti_name_of_b892a9_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionname',
            index=models.Index(fields=['name_english'], name='deqar_insti_name_en_cc303c_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionname',
            index=models.Index(fields=['acronym'], name='deqar_insti_acronym_94ad71_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionname',
            index=models.Index(fields=['name_valid_to'], name='deqar_insti_name_va_31ccbf_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionidentifier',
            index=models.Index(fields=['identifier_valid_to'], name='deqar_insti_identif_f50691_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionhistoricaldata',
            index=models.Index(fields=['valid_to'], name='deqar_insti_valid_t_c99cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='institutioncountry',
            index=models.Index(fields=['city'], name='deqar_insti_city_22426b_idx'),
        ),
        migrations.AddIndex(
            model_name='institutioncountry',
            index=models.Index(fields=['country_valid_to'], name='deqar_insti_country_7e92f4_idx'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['deqar_id'], name='deqar_insti_deqar_i_6dcf8c_idx'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['name_primary'], name='deqar_insti_name_pr_981189_idx'),
        ),
    ]
