# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='eter_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lists.ETEREntity'),
        ),
        migrations.AlterField(
            model_name='institutioncountry',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lists.Country'),
        ),
        migrations.AlterField(
            model_name='institutionidentifier',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agencies.Agency'),
        ),
        migrations.AlterField(
            model_name='institutionidentifier',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institutions.InstitutionResource'),
        ),
        migrations.AlterField(
            model_name='institutionqfehealevel',
            name='qf_ehea_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lists.QFEHEALevel'),
        ),
    ]
