# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='eter_id',
            new_name='eter',
        ),
    ]
