# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_auto_20171230_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutioneterrecord',
            options={'verbose_name': 'ETER Record', 'verbose_name_plural': 'ETER Records'},
        ),
        migrations.AlterModelOptions(
            name='institutionname',
            options={'ordering': ('institution', 'name_official', 'name_english'), 'verbose_name': 'Institution Name', 'verbose_name_plural': 'Institution Names'},
        ),
    ]
