# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_auto_20171113_2146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgencyHistoricalData',
            new_name='InstitutionHistoricalData',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='name_primary',
        ),
        migrations.AlterField(
            model_name='institutionnqflevel',
            name='nqf_level',
            field=models.CharField(max_length=10),
        ),
    ]
