# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_auto_20180205_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='deqar_id',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
