# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_auto_20171126_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionname',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
