# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_auto_20180107_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutioneterrecord',
            name='eter_link',
            field=models.URLField(blank=True),
        ),
    ]
