# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-17 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_auto_20180214_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionnameversion',
            name='name_version_source',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
