# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_auto_20180218_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='flag_log',
            field=models.TextField(blank=True),
        ),
    ]
