# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_institution_flag_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionname',
            name='acronym',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
