# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-01 08:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_auto_20180221_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionRelationship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship_note', models.CharField(blank=True, max_length=300, null=True)),
                ('relationship_date', models.DateField(default=datetime.date.today)),
                ('institution_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_source', to='institutions.Institution')),
                ('institution_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_target', to='institutions.Institution')),
            ],
            options={
                'verbose_name': 'Institution Relationship',
                'verbose_name_plural': 'Institution Relationships',
                'db_table': 'deqar_institution_relationships',
            },
        ),
        migrations.CreateModel(
            name='InstitutionRelationshipType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_from', models.CharField(max_length=200)),
                ('type_to', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Institution Relationship Type',
                'verbose_name_plural': 'Institution Relationship Types',
                'db_table': 'deqar_institution_relationship_types',
            },
        ),
        migrations.AddField(
            model_name='institutionrelationship',
            name='relationship_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.InstitutionRelationshipType'),
        ),
    ]
