# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-06 21:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_auto_20180221_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionHierarchicalRelationship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship_note', models.CharField(blank=True, max_length=300, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Institution Hierarchical Relationship',
                'verbose_name_plural': 'Institution Hierarchical Relationships',
                'db_table': 'deqar_institution_hierarchical_relationships',
            },
        ),
        migrations.CreateModel(
            name='InstitutionHistoricalRelationship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship_note', models.CharField(blank=True, max_length=300, null=True)),
                ('relationship_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'Institution Historical Relationship',
                'verbose_name_plural': 'Institution Historical Relationships',
                'db_table': 'deqar_institution_historical_relationships',
            },
        ),
        migrations.CreateModel(
            name='InstitutionHistoricalRelationshipType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_from', models.CharField(max_length=200)),
                ('type_to', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Institution Historical Relationship Type',
                'verbose_name_plural': 'Institution Historical Relationship Types',
                'db_table': 'deqar_institution_historical_relationship_types',
            },
        ),
        migrations.AddField(
            model_name='institution',
            name='closure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='founding_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='national_identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='source_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institutionhistoricalrelationship',
            name='institution_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_source', to='institutions.Institution'),
        ),
        migrations.AddField(
            model_name='institutionhistoricalrelationship',
            name='institution_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_target', to='institutions.Institution'),
        ),
        migrations.AddField(
            model_name='institutionhistoricalrelationship',
            name='relationship_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.InstitutionHistoricalRelationshipType'),
        ),
        migrations.AddField(
            model_name='institutionhierarchicalrelationship',
            name='institution_child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_child', to='institutions.Institution'),
        ),
        migrations.AddField(
            model_name='institutionhierarchicalrelationship',
            name='institution_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_parent', to='institutions.Institution'),
        ),
    ]
