# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-09 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0009_auto_20180605_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='has_report',
            field=models.BooleanField(default=0),
        ),
    ]
