# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-29 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0010_institution_has_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='name_sort',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
