# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-31 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0011_institution_name_sort'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['name_sort'], name='deqar_insti_name_so_d54c9d_idx'),
        ),
    ]
