# Generated by Django 2.1 on 2018-08-25 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0012_auto_20180731_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='flag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='lists.Flag'),
        ),
    ]
