# Generated by Django 2.0.8 on 2019-01-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0014_auto_20190131_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='source_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='institutioncountry',
            name='country_source_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='institutionname',
            name='name_source_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='institutionnameversion',
            name='name_version_source_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='institutionnqflevel',
            name='nqf_level_source_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='institutionqfehealevel',
            name='qf_ehea_level_source_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
