# Generated by Django 2.0.13 on 2019-05-26 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0015_auto_20190131_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionHierarchicalRelationshipType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Institution Hierarchical Relationship Type',
                'verbose_name_plural': 'Institution Hierarchical Relationship Types',
                'db_table': 'deqar_institution_hierarchical_relationship_types',
            },
        ),
        migrations.AddField(
            model_name='institutionhierarchicalrelationship',
            name='relationship_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.InstitutionHierarchicalRelationshipType'),
        ),
    ]
