# Generated by Django 2.0.13 on 2019-05-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0016_auto_20190509_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ('name_primary',), 'verbose_name': 'Institution'},
        ),
        migrations.AlterModelOptions(
            name='institutioncountry',
            options={'verbose_name': 'Institution Country'},
        ),
        migrations.AlterModelOptions(
            name='institutionflag',
            options={'ordering': ['id', 'flag__id'], 'verbose_name': 'Institution Flag'},
        ),
        migrations.AlterModelOptions(
            name='institutionhistoricaldata',
            options={'verbose_name': 'Institution Historical Data'},
        ),
        migrations.AlterModelOptions(
            name='institutionhistoricalfield',
            options={'verbose_name': 'Institution Historical Field'},
        ),
        migrations.AlterModelOptions(
            name='institutionidentifier',
            options={'verbose_name': 'Institution Identifier'},
        ),
        migrations.AlterModelOptions(
            name='institutionnameversion',
            options={'verbose_name': 'Institution Name Version'},
        ),
        migrations.AlterModelOptions(
            name='institutionnqflevel',
            options={'verbose_name': 'Institution NQF Level'},
        ),
        migrations.AlterModelOptions(
            name='institutionqfehealevel',
            options={'verbose_name': 'Institution QF-EHEA Level'},
        ),
        migrations.AlterModelOptions(
            name='institutionupdatelog',
            options={'verbose_name': 'Institution Update Log'},
        ),
    ]
