# Generated by Django 2.0.13 on 2019-05-26 07:58

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20190223_1739'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0016_auto_20190526_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionFlag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flag_message', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('removed_by_eqar', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lists.Flag')),
            ],
            options={
                'db_table': 'deqar_institution_flags',
                'ordering': ['id', 'flag__id'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionUpdateLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'deqar_institution_update_log',
            },
        ),
        migrations.AddField(
            model_name='institution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='internal_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='other_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='institutionidentifier',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='institutionupdatelog',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution'),
        ),
        migrations.AddField(
            model_name='institutionupdatelog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutions_log_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutionflag',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.Institution'),
        ),
        migrations.AlterUniqueTogether(
            name='institutionflag',
            unique_together={('institution', 'flag_message')},
        ),
    ]
