# Generated by Django 2.2.13 on 2020-06-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0018_auto_20190526_0759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutioncountry',
            options={'ordering': ['-id'], 'verbose_name': 'Institution Country'},
        ),
        migrations.AlterModelOptions(
            name='institutionnameversion',
            options={'ordering': ['-id'], 'verbose_name': 'Institution Name Version'},
        ),
        migrations.AlterModelOptions(
            name='institutionnqflevel',
            options={'ordering': ['-id'], 'verbose_name': 'Institution NQF Level'},
        ),
        migrations.AlterModelOptions(
            name='institutionqfehealevel',
            options={'ordering': ['-id'], 'verbose_name': 'Institution QF-EHEA Level'},
        ),
    ]
