# Generated by Django 2.2.13 on 2020-08-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0020_institution_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutionqfehealevel',
            options={'ordering': ['qf_ehea_level__code'], 'verbose_name': 'Institution QF-EHEA Level'},
        ),
    ]
