# Generated by Django 2.2.24 on 2021-09-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0021_auto_20200815_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionidentifier',
            name='identifier',
            field=models.CharField(max_length=100),
        ),
    ]
