# Generated by Django 2.2.28 on 2023-01-15 21:20

from django.db import migrations
from django.db.models.signals import post_save

from institutions.signals import do_index_institutions_upon_institution_save


def merge_eter_ids(apps, schema_editor):
    Institution = apps.get_model('institutions', 'Institution')
    for inst in Institution.objects.all():
        inst.eter_identifier = inst.eter.eter_id if inst.eter else None
        post_save.disconnect(do_index_institutions_upon_institution_save, sender=Institution)
        inst.save()


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0023_institution_add_eter_20230115'),
    ]

    operations = [
        migrations.RunPython(merge_eter_ids, reverse_code=migrations.RunPython.noop),
    ]
