# Generated by Django 2.2.28 on 2023-01-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0024_institution_migrate_eter_ids_20230115'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='institution',
            name='deqar_insti_eter_id_0ebb8f_idx',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='eter',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='eter_identifier',
            new_name='eter_id',
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['eter_id'], name='deqar_insti_eter_id_c80e73_idx'),
        ),
    ]
