# Generated by Django 2.2.28 on 2023-01-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0025_institution_rename_eter_identifier_field_20230115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionhierarchicalrelationship',
            name='relationship_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institutionhistoricalrelationship',
            name='relationship_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
