# Generated by Django 2.2.28 on 2023-05-17 15:34

from django.db import migrations
from django.db.models import Count


def remove_duplicate_qfehea_levels(apps, schema_editor):
    InstitutionQFEHEALevel = apps.get_model('institutions', 'InstitutionQFEHEALevel')

    # Set qf_ehea_level_verified to True
    for iqf in InstitutionQFEHEALevel.objects.filter(qf_ehea_level_verified=False):
        iqf.qf_ehea_level_verified = True
        iqf.save()

    # Remove duplicates
    for duplicates in InstitutionQFEHEALevel.objects.values("institution", "qf_ehea_level").annotate(
            records=Count("institution")
    ).filter(records__gt=1):
        for iqf in InstitutionQFEHEALevel.objects.filter(
                institution=duplicates["institution"],
                qf_ehea_level=duplicates["qf_ehea_level"]
        )[1:]:
            iqf.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0026_auto_20230125_1845'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_qfehea_levels, reverse_code=migrations.RunPython.noop),
    ]
