# Generated by Django 2.2.28 on 2023-05-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0027_remove_duplicate_qfehea_levels_20230517_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionqfehealevel',
            name='qf_ehea_level_verified',
        ),
    ]
