# Generated by Django 2.2.28 on 2023-08-07 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0028_remove_institutionqfehealevel_qf_ehea_level_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionOrganizationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Institution Organization Type',
                'verbose_name_plural': 'Institution Organization Types',
                'db_table': 'deqar_institution_organization_types',
            },
        ),
        migrations.AddField(
            model_name='institution',
            name='is_alternative_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='organization_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.InstitutionOrganizationType'),
        ),
    ]
