# Generated by Django 2.2.28 on 2023-09-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0029_auto_20230807_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='source_of_information',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
