# Generated by Django 2.2.28 on 2023-09-03 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_identifiersource'),
        ('institutions', '0030_institution_source_of_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionidentifier',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.IdentifierSource'),
        ),
    ]
