# Generated by Django 2.2.28 on 2023-09-11 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0031_institutionidentifier_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionidentifier',
            name='source',
        ),
    ]
