# Generated by Django 2.2.28 on 2023-09-12 04:54

from django.db import migrations, models
import django.db.models.deletion


def create_identifier_sources(apps, schema_editor):
    InstitutionIdentifier = apps.get_model("institutions", "InstitutionIdentifier")
    IdentifierResource = apps.get_model("lists", "IdentifierResource")
    for identifier in InstitutionIdentifier.objects.all():
        if len(identifier.resource) < 50:
            identifier_resource, created = IdentifierResource.objects.get_or_create(
                resource=identifier.resource
            )
            identifier.resource_temp = identifier_resource
            identifier.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_auto_20230913_1027'),
        ('institutions', '0032_remove_institutionidentifier_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionidentifier',
            name='resource_temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.IdentifierResource'),
        ),
        migrations.AlterUniqueTogether(
            name='institutionidentifier',
            unique_together={('institution', 'agency', 'resource_temp')},
        ),
        migrations.RunPython(create_identifier_sources),
        migrations.RemoveField(
            model_name='institutionidentifier',
            name='resource',
        ),
        migrations.RenameField(
            model_name='institutionidentifier',
            old_name='resource_temp',
            new_name='resource',
        ),
        migrations.AlterUniqueTogether(
            name='institutionidentifier',
            unique_together={('institution', 'agency', 'resource')},
        ),
    ]
