# Generated by Django 2.2.28 on 2024-02-07 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0034_auto_20231107_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='is_alternative_provider',
            new_name='is_other_provider',
        ),
    ]
