# Generated by Django 2.2.28 on 2025-02-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0036_configure_meilisearch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstitutionETERRecord',
        ),
    ]
