# Generated by Django 4.2.19 on 2025-03-25 18:11

from django.db import migrations
from django.conf import settings

from eqar_backend.meilisearch import MeiliClient

def configure_index(apps, schema_editor):
    if hasattr(settings, "MEILI_API_URL"):
        meili = MeiliClient()
        meili.wait_for(meili.update_settings(meili.INDEX_INSTITUTIONS, {
            'filterableAttributes': [
                'is_other_provider',
                'organization_type',
                'locations.country.id',
                'locations.country_verified',
                'locations.lat',
                'locations.long',
                'qf_ehea_levels',
                'founding_date',
                'closure_date',
                'has_report',
                'agencies.id',
                'activity_types',
                'activity_groups',
                'crossborder',
                'status',
            ],
        }))


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0038_update_meilisearch_config'),
    ]

    operations = [
        migrations.RunPython(configure_index, reverse_code=migrations.RunPython.noop),
    ]
