# Generated by Django 4.2.19 on 2026-07-06 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0039_meili_add_activity_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutionhierarchicalrelationship',
            options={'ordering': ('id',), 'verbose_name': 'Institution Hierarchical Relationship', 'verbose_name_plural': 'Institution Hierarchical Relationships'},
        ),
        migrations.AlterModelOptions(
            name='institutionidentifier',
            options={'ordering': ('agency', 'resource', 'identifier'), 'verbose_name': 'Institution Identifier'},
        ),
    ]
