# Generated by Django 4.2.19 on 2026-07-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0040_alter_institutionhierarchicalrelationship_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionname',
            name='orgreg_char_type',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
